version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=stori
      - POSTGRES_USER=stori
      - POSTGRES_PASSWORD=stori
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:3000
    environment:
      - POSTGRES_NAME=stori
      - POSTGRES_USER=stori
      - POSTGRES_PASSWORD=stori
    volumes:
      - .:/code
    ports:
      - "3000:3000"
    depends_on:
      - db
