# Generated by Django 4.1 on 2022-08-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='transactions_amount',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
